name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install

    - name: Lint with flake8
      run: |
        poetry run flake8 .

    - name: Format with black
      run: |
        poetry run black --check .

    - name: Test with pytest
      run: |
        poetry run pytest tests
